import AnimatedText from '@/components/AnimatedText'
import { LinkArrow } from '@/components/Icons'
import Layout from '@/components/Layout'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import profilePic from "../../public/images/profile/Ramisha2.jpg"
export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className="flex items-center w-full min-h-screen text-dark dark:text-light">
        <Layout>
          <div className='flex items-center justify-evenly w-full'>
            <div className='w-1/3'>
              <Image src={profilePic} className="rounded-full" priority sizes='(max-width:768px) 100vw, (max-width:1200px) 50vw, 50vw' />
            </div>
            <div className='w-1/2 flex flex-col items-center self-center'>
              <AnimatedText text={"Turning Vision Into Reality With Code And Design."} className="text-6xl text-left"/>
              <p className='text-base my-4 font-medium'>
                As a skilled full-stack developer, I am dedicated to turning ideas into innovative web applications.
                Explore my latest projects and articles, showcasing my expertise in React.js and web development.
              </p>
              <div className='flex items-center self-start mt-2'>
                <Link href="/CV.pdf" target="_blank" className='flex items-center p-2.5 px-6 rounded-lg bg-dark text-light dark:bg-light dark:text-dark font-semibold text-lg hover:text-dark hover:bg-light hover:dark:bg-dark hover:dark:text-light hover:dark:border-light border-solid border-transparent border-2 hover:border-dark'>
                  Resume
                  <LinkArrow className="w-[20px] ml-2"/>
                  </Link>
                <Link href="mailto:ramishaaa27@gmail.com" className='ml-4 text-lg underline capitalize text-dark font-medium dark:text-light'>Contact</Link>
              </div>
            </div>
          </div>
        </Layout>
      </main>
    </>
  )
}
